export const categories = [
  {
    animais: [
      'Animal Domestico',
      'Animal Aquatico',
      'Animal Africano',
      'Animal Voador',
      'Animal Pre-historico',
      'Animal Famoso',
      'Animal Ficticio',
      'Animal de Fazenda',
    ],
  },
  {
    pessoas: [
      'Pessoa de livro',
      'Pessoa Famosa de TV',
      'Pessoa Historica Famosa',
      'Pessoa Ficticia',
      'Celebridade',
      'Profissão',
      'Personagem de desenho',
      'Personagem de filme',
      'Ator',
      'Atriz',
      'Cantor Americano',
      'Cantora Brasileira',
      'Musico Famoso',
      'Politico Famoso',
    ],
  },
  {
    anime: [
      'Anime Famoso',
      'Anime não Famoso',
      'Anime Antigo',
      'Anime Atual',
      'Personagem de Anime',
      'Mangá',
      'Desenho Japones',
    ],
  },
  {
    ano: [
      'Ano Antigo',
      'Ano Atual',
      'Ano historico',
      'Ano Famoso',
      'Ano de algum acontecimento',
    ],
  },
  {
    filme: [
      'Filme Famoso',
      'Filme Antigo',
      'Filme Atual',
      'Filme Classico',
      'Seriado',
      'Animação',
      'Filme de Terror',
      'Filme de Ação',
      'Filme de Comedia',
      'Filme de Romance',
      'Filme de Ficção',
      'Filme de Aventura',
      'Filme de Suspense',
      'Filme de Drama',
      'Filme de Guerra',
      'Series de TV',
      'Ator',
      'Atriz',
      'Diretor',
    ],
  },
  {
    lugar: [
      'Lugar Famoso',
      'Lugar Historico',
      'Lugar Ficticio',
      'Pais',
      'Estado Brasileiro',
      'Cidades',
      'Lugar de filme',
      'Lugar de livro',
      'Locais famosos',
      'Locais de turismo',
      'Paradisiaco',
    ],
  },
  {
    biblia: [
      'Personagem Biblico',
      'Lugar Biblico',
      'Objeto Biblico',
      'Acontecimento Biblico',
      'Simbolo Biblico',
    ],
  },
  {
    esportes: [
      'Times de futebol',
      'Esportes Olimpicos',
      'Esportes Radicais',
      'Jogadores Famosos',
      'Atletas Famosos',
      'Objetos de esportes',
      'Esportes de inverno',
      'Esportes de verão',
    ],
  },
]
